### ISSUE TITLE
[REFACTOR] 모듈화

### ISSUE THREAD

**Issue by kooqooo** [boostcampaitech6/level2-klue-nlp-04#37]
## Background
- train.py가 300 줄이 넘고 길어서 코드를 보기가 어렵습니다.

## To do 
- [ ] ~~early stopping callback 클래스 모듈화~~
- [x] `metrics.py`: 평가지표로 사용되는 f1, auprc, acc 계산, difference.csv 생성
- [x] `load_data.py`: yaml 불러오기, label <-> num 상호전환, inference용 load_test_dataset() 
- [x] `inference.py`: 학습된 batch_size와 일치 시키기, config대로 inference 모델 지정하기

## 기능 체크리스트
- [x] 실행 전 hyper parameters가 예쁘게 출력되는지?
- [x] 실행 후 validation의 결과가 예쁘게 출력되는지?

**Comment by kooqooo** [comment]
클래스 모듈화에서 버그 발견했습니다.
```
Traceback (most recent call last):
  File "code/train.py", line 221, in <module>
    main()
  File "code/train.py", line 207, in main
    train()
  File "code/train.py", line 110, in train
    early_stopping_callback = EarlyStoppingCallback(
TypeError: __init__() got an unexpected keyword argument 'early_stopping_metric'
```

**Comment by kooqooo** [comment]
모듈화 새버전으로 찾아뵙겠습니다.
